### ISSUE TITLE
Use of closed network connection

### ISSUE THREAD

**Issue by EnchanterIO** [b00f/ethermint-private-network#1]
Hey boof,

I keep getting the: Error reading message: read tcp 127.0.0.1:46658->127.0.0.1:57612: use of closed network connection

I have the latest version of ethermint and go version: go version go1.10 darwin/amd64

Did you encounter this issue before?

Thx!

**Comment by b00f** [comment]
It's because of changes in tendermint (version 0.16.0)
Read here: https://github.com/tendermint/ethermint#ethermint
``` The latest version of Ethermint only works with Tendermint up to 0.14.0.```

If you downgrade your tendermint , you can run both of them. Otherwise we need to stay for ethermint update.

**Comment by EnchanterIO** [comment]
Hmm I see. I thought I have the version 0.14 actually as I installed it while ago but you are right, 0.16.0 is the one I have.

➜  ~ ethermint version
ethermint:  0.5.3-deb7883
go-ethereum:  1.6.7-stable
➜  ~ tendermint version
0.16.0

... will try to downgrade. Thx for the info!

**Comment by b00f** [comment]
If it worked for that version please close this bug

**Comment by EnchanterIO** [comment]
Ok. Will test it in the afternoon!

**Comment by EnchanterIO** [comment]
It actually worked! Even sending a transaction as u stated. Do you have a whatsapp/telegram ? 

I am experienced OOP engineer looking for some contacts in blockchain to chat with about the technology, new tools, frameworks etc. I also have a side project maybe you would like to join. 

Closing the issue!

**Comment by b00f** [comment]
Great. 
You can reach me by email address. It's in my profile. ;)
